version: '3'
services:
  airflow:
    image: apache/airflow:2.7.1-python3.10
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./my_crypto_project:/opt/airflow/my_crypto_project
      - ./fetch_crypto.py:/opt/airflow/fetch_crypto.py
    ports:
      - "8080:8080"
    command: standalone
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow