version: 2

models:
  - name: stg_crypto
    columns:
      - name: coin_id
        tests:
          - not_null  # Kiểm tra xem có dòng nào bị trống ID không

  - name: fct_crypto_prices
    columns:
      - name: coin_id
        tests:
          - unique    # Ở tầng Silver, ID không được phép trùng (vì ta đã deduplicate)
          - not_null
      - name: symbol
        tests:
          - not_null
      - name: price_usd
        tests:
          - accepted_values:
              values: [0]
              quote: false
              # Ở đây ta có thể dùng custom test nhưng tạm thời check đơn giản